### ISSUE TITLE
KeyStoreService.del null object reference on HUAWEI device 7.0

### ISSUE THREAD

**Issue by Gaetano-Dati** [iamMehedi/Secured-Preference-Store#25]
java.lang.RuntimeException: Unable to create application com.bananasrl.banana.Utils.App: java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.del(java.lang.String, int)' on a null object reference
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5678)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.del(java.lang.String, int)' on a null object reference
	at android.security.KeyStore.delete(KeyStore.java:186)
	at android.security.Credentials.deletePrivateKeyTypeForAlias(Credentials.java:292)
	at android.security.Credentials.deleteAllTypesForAlias(Credentials.java:251)
	at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:329)
	at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:580)
	at devliving.online.securedpreferencestore.EncryptionManager.generateAESKey(EncryptionManager.java:502)
	at devliving.online.securedpreferencestore.EncryptionManager.generateKey(EncryptionManager.java:472)
	at devliving.online.securedpreferencestore.EncryptionManager.setup(EncryptionManager.java:145)
	at devliving.online.securedpreferencestore.EncryptionManager.<init>(EncryptionManager.java:124)
	at devliving.online.securedpreferencestore.SecuredPreferenceStore.<init>(SecuredPreferenceStore.java:42)
	at devliving.online.securedpreferencestore.SecuredPreferenceStore.init(SecuredPreferenceStore.java:87)
	at com.bananasrl.banana.Utils.App.onCreate(App.java:111)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5659)
	... 8 more

**Comment by Gaetano-Dati** [comment]
@iamMehedi please can you tell me something about It? Thanks

**Comment by iamMehedi** [comment]
Huawei devices are encountering a few issues and most probably that has to
do something with the device's keystore implementation. I'll take a closer
look at this tomorrow and let you know if I can find anything.

**Comment by Gaetano-Dati** [comment]
Ok, the client is waiting for my Application which also contains your library.
Thank you very much.

**Comment by iamMehedi** [comment]
@Gaetano-Dati the error is happening in internal code of the `KeyGenerator`

**Comment by Gaetano-Dati** [comment]
And how can I delete this error? Modify something into the KeyGenerator class?
Can you do it and publish new version? 
I'm about to publish the application.
Thanks

**Comment by iamMehedi** [comment]
It's an internal issue of android/huawei's Keystore implementation, so there's nothing to fix in the library in particular.

**Comment by Gaetano-Dati** [comment]
Uhmm so the crash remains? And we can't deal with it? Ok. Thanks

**Comment by Gaetano-Dati** [comment]
I'm afraid that this problem will happen on every Huawei device.

**Comment by iamMehedi** [comment]
As the issue seems to be with the OS on Huawei devices, this will happen on all their devices at least the ones that are running the same version of the OS.

**Comment by javichaques** [comment]
Hello,

I have the same issue in my Huawei P8 Lite.

@Gaetano-Dati @iamMehedi 
Were you able to solve this? Workaround?

**Comment by Gaetano-Dati** [comment]
No, sorry. I'm still waiting for a solution

Il gio 31 mag 2018, 17:40 Javi Chaqués <notifications@github.com> ha
scritto:

**Comment by javichaques** [comment]
:( 
How are you save the preference ins this moment? @Gaetano-Dati 

Thank you

**Comment by maxkomarychev** [comment]
@Gaetano-Dati hey, did you get this error on actual device you have or it's from google pre-launch report or any other crash-reporting service (like crashlytics..)?

if first is true - did you by any chance tried this on any other android version on Huawei device?

**Comment by kutran** [comment]
I just saw this on our pre-launch report trying to start an internal test track.  I am wondering running this will cause the same problem on Huawei (or any other phones like ZTE).

I think FireBase has Android Testing on the cloud; I am going to try it out.

**Comment by xrom888** [comment]
I tried last version 0.7.0 on my Huawei P7 works well now.
