### ISSUE TITLE
java.lang.NoClassDefFoundError: devliving.online.securedpreferencestore.Logger on Android APi 19

### ISSUE THREAD

**Issue by djavid** [iamMehedi/Secured-Preference-Store#36]
Couln't launch app on Android emulator, Android 4.4 Api 19. Other api works correct.

`I/dalvikvm: Could not find method devliving.online.securedpreferencestore.EncryptionManager.getHashed, referenced from method devliving.online.securedpreferencestore.SecuredPreferenceStore.getStringSet
W/dalvikvm: VFY: unable to resolve static method 1011: Ldevliving/online/securedpreferencestore/EncryptionManager;.getHashed (Ljava/lang/String;)Ljava/lang/String;
D/dalvikvm: VFY: replacing opcode 0x71 at 0x0006
I/dalvikvm: Could not find method devliving.online.securedpreferencestore.Logger.e, referenced from method devliving.online.securedpreferencestore.SecuredPreferenceStore.getStringSet
W/dalvikvm: VFY: unable to resolve static method 1013: Ldevliving/online/securedpreferencestore/Logger;.e (Ljava/lang/Exception;)V
D/dalvikvm: VFY: replacing opcode 0x71 at 0x0039
            DexOpt: unable to opt direct call 0x03fe at 0x2b in Ldevliving/online/securedpreferencestore/SecuredPreferenceStore;.<init>
            DexOpt: unable to opt direct call 0x03fc at 0x37 in Ldevliving/online/securedpreferencestore/SecuredPreferenceStore;.<init>
            DexOpt: unable to opt direct call 0x03f0 at 0x3e in Ldevliving/online/securedpreferencestore/SecuredPreferenceStore;.<init>
            DexOpt: unable to opt direct call 0x03fd at 0x02 in Ldevliving/online/securedpreferencestore/SecuredPreferenceStore;.edit
D/AndroidRuntime: Shutting down VM
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x9cca8b20)
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: zam.wallet, PID: 3297
                  java.lang.NoClassDefFoundError: devliving.online.securedpreferencestore.Logger
                      at devliving.online.securedpreferencestore.SecuredPreferenceStore.<init>(SecuredPreferenceStore.java:67)
                      at devliving.online.securedpreferencestore.SecuredPreferenceStore.init(SecuredPreferenceStore.java:134)
`

**Comment by iamMehedi** [comment]
Sounds like a Multidex issue, see here:
https://github.com/realm/realm-java/issues/2837
